import { StyleSheet } from "react-native";

const LocationPermissionStyle = StyleSheet.create({
  gradientBackground: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
    paddingHorizontal: 20,
    paddingTop: 32,
    paddingBottom: 32,
  },
  container: {
    flex: 1,
    alignItems: "center",
  },
  imageShadow: {
    width: "100%",
    borderRadius: 22,
    padding: 8,
    backgroundColor: "#ffffff",
    shadowColor: "#ff365e",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.18,
    shadowRadius: 16,
    elevation: 10,
  },
  imageWrapper: {
    width: "100%",
    height: 210,
    borderRadius: 14,
    overflow: "hidden",
  },
  featureImage: {
    width: "100%",
    height: "100%",
    resizeMode: "cover",
  },
  headerBlock: {
    width: "100%",
    marginTop: 28,
    alignItems: "center",
  },
  title: {
    fontSize: 24,
    fontWeight: "800",
    color: "#1b1b1b",
    textAlign: "center",
  },
  subtitle: {
    marginTop: 12,
    fontSize: 14,
    color: "#6c6c6c",
    textAlign: "center",
    lineHeight: 20,
    paddingHorizontal: 8,
  },
  featureList: {
    width: "100%",
    marginTop: 22,
    gap: 12,
  },
  featureCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#ffffff",
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderRadius: 16,
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 10,
    elevation: 5,
  },
  featureIcon: {
    width: 44,
    height: 44,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  featureTextBlock: {
    flex: 1,
  },
  featureTitle: {
    fontSize: 15,
    fontWeight: "700",
    color: "#1b1b1b",
  },
  featureDescription: {
    fontSize: 13,
    color: "#777777",
    marginTop: 2,
    lineHeight: 18,
  },
  privacyRow: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 18,
    gap: 8,
    alignSelf: "center",
  },
  privacyText: {
    fontSize: 12,
    color: "#9a9a9a",
    letterSpacing: 1.1,
    fontWeight: "700",
  },
  buttonGroup: {
    width: "100%",
    marginTop: 24,
    gap: 12,
  },
  primaryButton: {
    borderRadius: 30,
    paddingVertical: 16,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#ff3562",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.24,
    shadowRadius: 14,
    elevation: 10,
  },
  primaryButtonText: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "700",
    letterSpacing: 0.2,
  },
  secondaryButton: {
    borderRadius: 24,
    paddingVertical: 14,
    backgroundColor: "#ffffff",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 6,
  },
  secondaryButtonText: {
    color: "#9a9a9a",
    fontSize: 14,
    fontWeight: "600",
    letterSpacing: 0.2,
  },
});

export default LocationPermissionStyle;
